Feature/general fixes2
sacha-buengueroff/respirar-modulo-estaciones-be pull request #10
Opened 2023-05-24 02:52 UTC by rodarg877

* Se cambiaron variables a camelCase
* Se agrego nuevo atributo estatico "enable" al modelo de datos para definir si la estacion esta suspendida o activa (Boolean)
* Se agrego suspenderEstacion en la ApiEstaciones
* Se agrego suspenderEstacion en el Controller
* Se agrego suspenderEstacion en el UlHttp el cual llama a la funcion suspender estacion en el context y elimina la estacion del iot agent no permitiendo que la misma provisione datos( no se elimina del context Broker)
* Se agrego suspenderEstacion en cbHttp la cual cambia el atributo "enable" a false.

2023-05-24 19:39 UTC, adrielgentil commented
Che, estas mergeando a main. Es esa la idea? o querias mergear algún cambio a develop?

2023-05-24 22:51 UTC, adrielgentil requested changes
La mayoria son boludeces, excepto lo de params

2023-05-24 22:51 UTC, adrielgentil commented on api/ApiEstaciones.js
> +        return this.cbHttp.getEstacionesPropias(user)
Tecnicamente, las propias son las de Ciudad. Pondría getEstacionesByUser, o algo asi

2023-05-24 22:51 UTC, adrielgentil commented on controller/estacionesController.js
> +    getEstacionesPropias = async(req, res) => {
Lo mismo que antes, pondría getEstacionesPorUsuario

2023-05-24 22:51 UTC, adrielgentil commented on httpMethods/agentUlHttp.js
> +                        },
Me parece que JSON no acepta coma dsp del último elemento, y entiendo que este es el último elemento del array atributes

2023-05-24 22:51 UTC, adrielgentil commented on httpMethods/agentUlHttp.js
> +                    mensaje: "se habilito correctamente el device " + id
Esto se aplica a todo, pero si estamos escribiendo en español, traduciría devices (y cualquier otra palabra) al español. En este caso dispositivo

2023-05-24 22:51 UTC, adrielgentil commented on httpMethods/cbHttp.js
> +            let respuesta = await axios.get(this.url + "v2/entities/?q=ownerId=='urn:ngsi-ld:" + user + "'&options=keyValues&type=AirQualityObserved", this.config)
Creo que los params no deberiamos hardcodearlos asi, sino pasarlos por parametros. Acá dejo un link de como hacerlo, pero basicamente es agregarlos a la config.
https://stackoverflow.com/questions/48261227/use-axios-get-with-params-and-config-together

2023-05-24 22:51 UTC, adrielgentil commented on router/estaciones.js
> +        this.router.get('/propias/:user', this.controladorEstaciones.getEstacionesPropias)
Lo mismo que antes, propias serían las de ciudad del futuro, acá habría que usar estacionesUsuario o algo asi.

2023-05-24 22:55 UTC, adrielgentil commented
Che, fijate que te tira que hay conflicto. Fijate de hacer un pull de la branch develop, y mergeala a tu rama, asi resolves los conflictos y podes mergear sin problema. Si no sabes como chiflá y lo vemos.

2023-05-25 21:12 UTC, sacha-buengueroff approved these changes

2023-05-25 21:19 UTC, adrielgentil approved these changes

2023-05-25 21:19 UTC, adrielgentil commented on httpMethods/agentUlHttp.js
> +            const respuesta = await axios.delete(this.url + "/devices" + "/" + id, this.config)
Se podría agregar la / al /devices, y que quede /devices/, asi la concatenacion queda mas limpia. Igualmente, no se si convendria usar este metodo
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat

2023-05-25 21:19 UTC, adrielgentil commented on httpMethods/cbHttp.js
> +            let respuesta = await axios.get(this.url + "v2/entities/?q=ownerId=='urn:ngsi-ld:" + user + "'&options=keyValues&type=AirQualityObserved", this.config)
Ahora que lo pienso, probablemente habria que ver de generar alguna validacion sobre usuario, no vaya a hacer que hagan alguna inyeccion maliciosa. Pero puede quedar para despues esto

2023-05-25 21:21 UTC, merged